### ISSUE TITLE
Invalid status 6a84

### ISSUE THREAD

**Issue by javroch** [parkerhoyes/bolos-app-otp2fa#1]
Whenever I run the installation command from: https://parkerhoyes.com/bolos-apps/bolos-app-otp2fa
```
Generated random root public key : 04e4d35407600310dc218afcc9d4a4dd771f3f190e341ed5ec768a6063496086163104851e5e5fa482f80d30f8430abaf763ce4a158701657e1c8e5821cd4efe38
Using test master key 04e4d35407600310dc218afcc9d4a4dd771f3f190e341ed5ec768a6063496086163104851e5e5fa482f80d30f8430abaf763ce4a158701657e1c8e5821cd4efe38 
Using ephemeral key 0467ccbf1c9c3479cd2808d8b264a0098c68100c589e681ee33ccf16df0b7ffc014788070320d6e96879010cc0507d77c9264ae51944eed71c243154a7eb844bfa
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/XXXXXX/Downloads/ledger/lib/python2.7/site-packages/ledgerblue/loadApp.py", line 174, in <module>
    loader.createApp(args.appFlags, appLength, args.appName, icon, path, None, None, args.appVersion)
  File "/home/XXXXXX/Downloads/ledger/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 164, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)				
  File "/home/XXXXXX/Downloads/ledger/local/lib/python2.7/site-packages/ledgerblue/hexLoader.py", line 86, in exchange
    return self.card.exchange(apdu)
  File "/home/XXXXXX/Downloads/ledger/local/lib/python2.7/site-packages/ledgerblue/comm.py", line 130, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6a84
```

I should have all the udev rules in place. Ledger Manager can interact with my Ledger Nano S just fine. Am I missing something, perhaps?

**Comment by javroch** [comment]
I apologize if that was a "newb" comment. I actually searched around and I *think* I might know the cause now. It seems that code might mean my device is out of space. I'll free up some space and try again. If I'm still having trouble. I'll re-open. Sorry for any annoyance.
